spring:
  application:
    name: example-ribbitmq

  rabbitmq:
    addresses: 192.168.56.3
   ##rabbitmq\u670D\u52A1\u4E0D\u5728\u672C\u5730\u65F6\u7528addresses\u94FE\u63A5\u5730\u5740\u5C5E\u6027\u94FE\u63A5
   ## host: 
    port: 15672
    username: root
    password: 123456
    
 
##hystrix